- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  #WL-Changes-start
  skillPoints: 22
  minAge: 26
  subnames:
  - хирург
  - вирусолог
  - генетик
  - патологоанатом
  #WL-Changes-end
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs # Corvax-RoleTime
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - BoxSurvivalMedical