- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  # Corvax WL
  #- CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - CorvaxMaus
  - CorvaxIshimura
  - CorvaxPaper
  - CorvaxSplit
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
