- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxAstra
  - CorvaxPilgrim
  - Box
  # Midpop
  - CorvaxPaper
  #- CorvaxPearl — До реворка
  - CorvaxOutpost
  - CorvaxAwesome
  - Bagel
  - Marathon
  #- Train — До реворка оффами
  # Lowpop
  - CorvaxSilly
  - CorvaxAstra
  - CorvaxMaus
  - CorvaxPaper
  - CorvaxPilgrim
  - CorvaxTerra
  - CorvaxPearl
  - NanoStation
  - CorvaxTushkan
  - CorvaxGlacier
  - Bagel
  - Box
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  #- Train
