using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;
using System.Linq;

namespace Content.Client._WL.Passports.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ChameleonPassportWindow : DefaultWindow
    {
        public event Action<string>? OnNameChanged;
        public event Action<string>? OnSpeciesChanged;
        public event Action<string>? OnGenderChanged;
        public event Action<string>? OnYOBChanged;
        public event Action<string>? OnHeightChanged;
        public event Action<string>? OnPIDChanged;

        public ChameleonPassportWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            NameLineEdit.OnTextEntered += e => OnNameChanged?.Invoke(e.Text);
            NameLineEdit.OnFocusExit += e => OnNameChanged?.Invoke(e.Text);

            SpeciesLineEdit.OnTextEntered += e => OnSpeciesChanged?.Invoke(e.Text);
            SpeciesLineEdit.OnFocusExit += e => OnSpeciesChanged?.Invoke(e.Text);

            GenderLineEdit.OnTextEntered += e => OnGenderChanged?.Invoke(e.Text);
            GenderLineEdit.OnFocusExit += e => OnGenderChanged?.Invoke(e.Text);

            YOBLineEdit.OnTextEntered += e => OnYOBChanged?.Invoke(e.Text);
            YOBLineEdit.OnFocusExit += e => OnYOBChanged?.Invoke(e.Text);

            HeightLineEdit.OnTextEntered += e => OnHeightChanged?.Invoke(e.Text);
            HeightLineEdit.OnFocusExit += e => OnHeightChanged?.Invoke(e.Text);

            PIDLineEdit.OnTextEntered += e => OnPIDChanged?.Invoke(e.Text);
            PIDLineEdit.OnFocusExit += e => OnPIDChanged?.Invoke(e.Text);
        }

        public void SetCurrentName(string name)
        {
            NameLineEdit.Text = name;
        }

        public void SetCurrentSpecies(string species)
        {
            SpeciesLineEdit.Text = species;
        }

        public void SetCurrentGender(string gender)
        {
            GenderLineEdit.Text = gender;
        }

        public void SetCurrentYOB(string YearOfBirth)
        {
            YOBLineEdit.Text = YearOfBirth;
        }

        public void SetCurrentHeight(string height)
        {
            HeightLineEdit.Text = height;
        }

        public void SetCurrentPID(string PID)
        {
            PIDLineEdit.Text = PID;
        }
    }
}
