using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEmojiPopup : DefaultWindow
{
    public Action<string>? OnEmojiSelected;

    // Holy Shit! It's 232 emoji
    private readonly List<string> _emojis = new()
    {
        "♥", "★", "☆", "⚝", "⚜", "⚚", "⚛", "♻",
        "☮", "☯", "☣", "☢", "☠", "♿", "⚕", "⚧",

        "←", "→", "↑", "↓", "↔", "↕", "↖", "↗",
        "↘", "↙", "⌂", "⌃", "⌄",

        "±", "×", "÷", "≈", "≠", "≡", "≤", "≥",
        "√", "∞", "∫", "∂", "∆", "⌘", "⌥", "⌦",
        "⌫", "⎋", "⏎", "⌤", "⌧",

        "⌚", "⏱", "⏲", "⏳", "⌛",
        "🕐", "🕑", "🕒", "🕓", "🕔", "🕕", "🕖", "🕗",
        "🕘", "🕙", "🕚", "🕛", "🕜", "🕝", "🕞", "🕟",

        "☀", "☁", "☂", "☃", "❄", "⚡", "☄", "🌍",
        "🌎", "🌏", "🌕", "⭐",

        "●", "○", "◆", "◇", "■", "□", "▲", "△",
        "▼", "▽", "▶", "▷", "◀", "◁", "★", "☆",
        "☐", "☑", "☒", "▪", "▫", "◊", "◦", "◌",

        "♪", "♫", "♬",  "🎧",

        "♠", "♣", "♥", "♦", "♤", "♧", "♡", "♢",

        "♔", "♕", "♖", "♗", "♘", "♙", "♚", "♛",
        "♜", "♝", "♞", "♟", "🎮", "🕹",

        "✉", "📤", "📥", "📦", "📫",
        "📪", "📬", "📭", "✏", "✒",
        "🏷", "💰",

        "🏎", "🚑", "🚲", "🚍", "🚔", "⚓", "✈", "🛩",

        "🌶", "🍸",

        "🐦", "🕷", "🐟", "🐕", "🐈", "🪶","🕊", "🐿",

        "🪵", "☘", "🪨", "🌜",

        "☹", "😐", "👽",

        "🖐", "✋", "👌", "✌", "👈", "👉", "👆", "👇",
        "☝", "👍", "👎", "✍", "👂", "👁", "⛷", "🏂",
        "🏌", "🏄", "🏊", "⛹", "🏋", "👪", "🗣", "🫂",
        "🌡", "🩸", "🩹", "🩺", "🛏", "🛋", "🗺", "🏔",
        "⛰", "🏕", "🏖", "🏜", "🏝", "🏞", "🏟", "🏛", "🏗",
        "🪨", "🪵", "🛖", "🏘", "🏚", "🏠", "🏭", "⛪",
        "🛕", "⛩", "⛲", "🏙", "♨", "🛎", "☂", "👓",
        "🕶", "🩱", "🩲", "🩳", "🛍", "🩰", "🎓", "⛑",
        "🔇", "🔈", "🔉", "🔊", "🎙", "🎚", "🎛", "🎧",
        "📻", "☎", "📟", "💻", "🖥", "🖨", "⌨", "🖱", "🖲", "📽",
    };

    public NanoChatEmojiPopup()
    {
        RobustXamlLoader.Load(this);

        PopulateEmojis();
    }

    private void PopulateEmojis()
    {
        foreach (var emoji in _emojis)
        {
            var button = new Button
            {
                Text = emoji,
                MinSize = new Vector2(40, 40),
                HorizontalExpand = true
            };

            button.OnPressed += _ =>
            {
                OnEmojiSelected?.Invoke(emoji);
                Close();
            };

            EmojiContainer.AddChild(button);
        }
    }
}
