- type: entity
  id: ThrusterSmallMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small thruster machine board
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: ThrusterSmall
    stackRequirements:
      Capacitor: 2
      Steel: 5
      MetalRod: 2
