using Content.Shared._WL.Languages;
using Content.Shared._WL.Languages.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WL.UserInterface.Systems.Languages.LanguageUI;

[GenerateTypedNameReferences]
public sealed partial class LanguageItemControl : BoxContainer
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private readonly SpriteSystem _sprite = default!;

    private ProtoId<LanguagePrototype> _languageId;
    private LanguageLevel _languageLevel;

    public event Action<ProtoId<LanguagePrototype>>? OnChoosePressed;

    public LanguageItemControl()
    {
        new LanguageItemControl("Translate", 0);
    }

    public LanguageItemControl(ProtoId<LanguagePrototype> languageId, LanguageLevel level)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entMan.System<SpriteSystem>();

        _languageId = languageId;
        _languageLevel = level;

        ChooseButton.OnPressed += _ => OnChoosePressed?.Invoke(_languageId);
        UpdateData();
    }

    public void SetData(ProtoId<LanguagePrototype>? protoId = null, LanguageLevel? level = null)
    {
        _languageId = protoId ?? _languageId;
        _languageLevel = level ?? _languageLevel;

        UpdateData();
    }

    public void SetButtonState(bool state)
    {
        ChooseButton.Pressed = state;
    }

    private void UpdateData()
    {
        if (!_protoMan.TryIndex(_languageId, out var language))
            return;

        var titleMessage = new FormattedMessage();
        var descriptionMessage = new FormattedMessage();

        titleMessage.AddText(Loc.GetString(
                "ui-languages-item-title",
                ("name", Loc.GetString(language.Name)),
                ("level", (int)_languageLevel)
            )
        );

        var subtitleMessage = Loc.GetString(
            "ui-languages-item-subtitle",
            ("color", language.Color),
            ("keychar", language.KeyLanguage)
        );

        descriptionMessage.AddText(Loc.GetString(language.Description));

        Title.SetMessage(titleMessage);
        Subtitle.Text = subtitleMessage;
        Description.SetMessage(descriptionMessage);

        Icon.Texture = _sprite.Frame0(language.Icon);

        ChooseButton.Disabled = _languageLevel < LanguageLevel.Good;
    }
}
