using Content.Shared._WL.Emergency;
using Content.Shared.AlertLevel;
using Content.Shared.Communications;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Communications.UI;

/// <summary>
/// The main menu for the communications console interface.
/// Contains a series of widgets for the alert, announce/broadcast and shuttle functions.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CommunicationsConsoleMenu : FancyWindow
{
    public event Action? OnShuttleCalled;
    public event Action? OnShuttleRecalled;
    public event Action<ProtoId<AlertLevelPrototype>>? OnAlertLevelChanged;
    public event Action<ProtoId<EmergencyLevelPrototype>>? OnEmergencyLevelChanged; // WL-Changes: Emergency
    public event Action<string>? OnRadioAnnounce;
    public event Action<string>? OnScreenBroadcast;

    public CommunicationsConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MessagingControls.OnRadioAnnounce += message => OnRadioAnnounce?.Invoke(message);
        MessagingControls.OnScreenBroadcast += message => OnScreenBroadcast?.Invoke(message);

        AlertLevelControls.OnAlertLevelChanged += newLevel => OnAlertLevelChanged?.Invoke(newLevel);
        EmergencyLevelControls.OnEmergencyLevelChanged += newLevel => OnEmergencyLevelChanged?.Invoke(newLevel); // WL-Changes: Emergency

        ShuttleControls.OnShuttleCalled += () => OnShuttleCalled?.Invoke();
        ShuttleControls.OnShuttleRecalled += () => OnShuttleRecalled?.Invoke();
    }

    /// <summary>
    /// Use the specified prototype ID as an example display in the
    /// UI subsection where users type broadcast messages
    /// </summary>
    public void SetBroadcastDisplayEntity(EntProtoId broadcastEntityId)
    {
        MessagingControls.SetBroadcastDisplayEntity(broadcastEntityId);
    }

    /// <summary>
    /// Configure UI to be consistent with the input state
    /// </summary>
    public void UpdateState(CommunicationsConsoleInterfaceState commsState,
        ProtoId<AlertLevelPrototype> currentAlertLevel,
        List<ProtoId<AlertLevelPrototype>>? selectableAlertLevels,
        bool canChangeAlertLevel,
        // WL-Changes-start: Emergency
        ProtoId<EmergencyLevelPrototype> currentEmergencyLevel,
        List<ProtoId<EmergencyLevelPrototype>>? selectableEmergencyLevels,
        bool canChangeEmergencyLevel)
        // WL-Changes-end
    {
        MessagingControls.CanRadioAnnounce = commsState.CanAnnounce;
        MessagingControls.CanScreenBroadcast = commsState.CanBroadcast;

        var alertLevelSelectable = selectableAlertLevels != null && canChangeAlertLevel;
        AlertLevelControls.UpdateAlertLevels(selectableAlertLevels, currentAlertLevel, alertLevelSelectable);

        // WL-Changes-start: Emergency
        var emergencyLevelSelectable = selectableEmergencyLevels != null && canChangeEmergencyLevel;
        EmergencyLevelControls.UpdateEmergencyLevels(selectableEmergencyLevels, currentEmergencyLevel, emergencyLevelSelectable);
        // WL-Changes-end

        ShuttleControls.UpdateState(commsState.CanCall, commsState.CountdownStarted, commsState.ExpectedCountdownEnd);
    }
}
