//WL-Changes-NanoChat-Start
using Content.Shared._WL.CartridgeLoader.Cartridges;
//WL-Changes-NanoChat-End
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    /// <summary>
    /// Action invoked when the print button gets pressed.
    /// </summary>
    public Action? OnPrintPressed;

    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    //WL-Changes-NanoChat-Start
    public void UpdateState(string name, List<PulledAccessLog> logs, NanoChatData? nanoChat = null)
    {
        EntityName.Text = name;
        PrintButton.Disabled = string.IsNullOrEmpty(name);

        ProbedDeviceContainer.RemoveAllChildren();

        var count =  1;
        foreach (var log in logs)
        {
            AddAccessLog(log, count);
            count++;
        }

        UpdateNanoChat(nanoChat);
    }

    private void UpdateNanoChat(NanoChatData? nanoChat)
    {
        NanoChatContactsContainer.RemoveAllChildren();

        if (nanoChat is not { } data)
        {
            NanoChatContainer.Visible = false;
            return;
        }

        NanoChatContainer.Visible = true;
        NanoChatHeader.Text = data.CardNumber is { } number
            ? Loc.GetString("log-probe-nanochat-header", ("number", number.ToString("D4")))
            : Loc.GetString("log-probe-nanochat-header-no-number");

        foreach (var (recipientNumber, recipient) in data.Recipients)
        {
            var messageCount = data.Messages.TryGetValue(recipientNumber, out var messages) ? messages.Count : 0;
            NanoChatContactsContainer.AddChild(new Label
            {
                Text = Loc.GetString("log-probe-nanochat-contact",
                    ("name", recipient.Name),
                    ("number", recipientNumber.ToString("D4")),
                    ("count", messageCount)),
            });
        }
    }
    //WL-Changes-NanoChat-End

    private void AddAccessLog(PulledAccessLog log, int numberLabelText)
    {
        var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
        var accessorLabelText = log.Accessor;
        var entry = new LogProbeUiEntry(numberLabelText, timeLabelText, accessorLabelText);

        ProbedDeviceContainer.AddChild(entry);
    }
}
