using System;
using System.Numerics;
using Content.Client._WL.Skills;
using Content.Client.Message;
using Content.Shared._WL.Construction;
using Content.Shared._WL.Skills.Components;
using Content.Shared._WL.Skills.Systems;
using Content.Shared.Construction.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;


namespace Content.Client.Construction.UI
{
    /// <summary>
    /// This is the interface for a UI View of the construction window. The point of it is to abstract away the actual
    /// UI controls and just provide higher level operations on the entire window. This View is completely passive and
    /// just raises events to the outside world. This class is controlled by the <see cref="ConstructionMenuPresenter"/>.
    /// </summary>
    public interface IConstructionMenuView : IDisposable
    {
        // It isn't optimal to expose UI controls like this, but the UI control design is
        // questionable so it can't be helped.
        string[] Categories { get; set; }
        OptionButton Category { get; }

        bool EraseButtonPressed { get; set; }
        bool BuildButtonPressed { get; set; }

        ItemList Recipes { get; }
        ItemList RecipeStepList { get; }

        event EventHandler<(string search, string catagory)> PopulateRecipes;
        event EventHandler<ItemList.Item?> RecipeSelected;
        event EventHandler<bool> BuildButtonToggled;
        event EventHandler<bool> EraseButtonToggled;
        event EventHandler ClearAllGhosts;

        void ClearRecipeInfo();
        void SetRecipeInfo(
            string name,
            string description,
            Texture iconTexture,
            bool isItem,
            /*WL-Skills-start*/ConstructionPrototype? prototype/*WL-Skills-end*/);
        void ResetPlacement();

        #region Window Control

        event Action? OnClose;

        bool IsOpen { get; }

        void OpenCentered();
        void MoveToFront();
        bool IsAtFront();
        void Close();

        #endregion
    }

    [GenerateTypedNameReferences]
    public sealed partial class ConstructionMenu : DefaultWindow, IConstructionMenuView
    {
        //WL-Skills-start
        [Dependency] private readonly IPlayerManager _playMan = default!;
        [Dependency] private readonly IEntityManager _entMan = default!;
        [Dependency] private readonly IPrototypeManager _protoMan = default!;

        private readonly ClientSkillsSystem _skills;
        //WL-Skills-end

        public bool BuildButtonPressed
        {
            get => BuildButton.Pressed;
            set => BuildButton.Pressed = value;
        }

        public string[] Categories { get; set; } = Array.Empty<string>();

        public bool EraseButtonPressed
        {
            get => EraseButton.Pressed;
            set => EraseButton.Pressed = value;
        }

        public ConstructionMenu()
        {
            SetSize = MinSize = new Vector2(890, 320);

            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Title = Loc.GetString("construction-menu-title");

            BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
            Recipes.OnItemSelected += obj => RecipeSelected?.Invoke(this, obj.ItemList[obj.ItemIndex]);
            Recipes.OnItemDeselected += _ => RecipeSelected?.Invoke(this, null);

            SearchBar.OnTextChanged += _ => PopulateRecipes?.Invoke(this, (SearchBar.Text, Categories[Category.SelectedId]));
            Category.OnItemSelected += obj =>
            {
                Category.SelectId(obj.Id);
                PopulateRecipes?.Invoke(this, (SearchBar.Text, Categories[obj.Id]));
            };

            BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
            BuildButton.OnToggled += args => BuildButtonToggled?.Invoke(this, args.Pressed);
            ClearButton.Text = Loc.GetString("construction-menu-clear-all");
            ClearButton.OnPressed += _ => ClearAllGhosts?.Invoke(this, EventArgs.Empty);
            EraseButton.Text = Loc.GetString("construction-menu-eraser-mode");
            EraseButton.OnToggled += args => EraseButtonToggled?.Invoke(this, args.Pressed);

            //WL-Skills-start
            _skills = _entMan.System<ClientSkillsSystem>();
            //WL-Skills-end
        }

        public event EventHandler? ClearAllGhosts;

        public event EventHandler<(string search, string catagory)>? PopulateRecipes;
        public event EventHandler<ItemList.Item?>? RecipeSelected;
        public event EventHandler<bool>? BuildButtonToggled;
        public event EventHandler<bool>? EraseButtonToggled;

        public void ResetPlacement()
        {
            BuildButton.Pressed = false;
            EraseButton.Pressed = false;
        }

        public void SetRecipeInfo(
            string name,
            string description,
            Texture iconTexture,
            bool isItem,
            /*Wl-Skills-start*/ConstructionPrototype? prototype/*WL-Skills-end*/)
        {
            BuildButton.Disabled = false;
            BuildButton.Text = Loc.GetString(isItem ? "construction-menu-place-ghost" : "construction-menu-craft");
            TargetName.SetMessage(name);
            TargetDesc.SetMessage(description);
            TargetTexture.Texture = iconTexture;

            //WL-Skills-start
            var entity = _playMan?.LocalEntity;
            if (entity == null)
                return;

            if (!_entMan.TryGetComponent<SkillsHolderComponent>(entity, out var skillsHolderComp))
                return;

            var conditions = prototype?.RequiredSkills;
            if (conditions == null || conditions.Count == 0)
            {
                InfoBox.HorizontalAlignment = HAlignment.Center;
                return;
            }
            else
            {
                InfoBox.HorizontalAlignment = HAlignment.Left;
                ConstructionConditions.AddChild(new Label() { Text = "Требуемые навыки:"});
            }

            foreach (var condition in conditions)
            {
                var proto = _protoMan.Index(condition.Key);

                var label = new RichTextLabel()
                {
                    Margin = new(0, 2, 5, 2)
                };
                var skillColor = proto.NameColor ?? Color.White;

                var symbol = _skills.HasSkillMin((entity.Value, skillsHolderComp), condition.Key, condition.Value)
                    ? $"[head=2][color={Color.Green.ToHex()}]+[/color][/head]"
                    : $"[head=2][color={Color.Red.ToHex()}]-[/color][/head]";

                label.SetMarkup($"{symbol} [color={skillColor.ToHex()}]{proto.Name}[/color]: {SharedSkillsSystem.GetSkillLocName(condition.Value)}");

                ConstructionConditions.AddChild(label);
            }
            //WL-Skills-end
        }

        public void ClearRecipeInfo()
        {
            BuildButton.Disabled = true;
            TargetName.SetMessage(string.Empty);
            TargetDesc.SetMessage(string.Empty);
            TargetTexture.Texture = null;
            RecipeStepList.Clear();
            //WL-Skills-start
            ConstructionConditions.RemoveAllChildren();
            //WL-Skill-end
        }
    }
}
