- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  subnames:
  - ассистент
  - художник
  - юрист
  - фрилансер
  - экипаж вне службы
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
#  access: # Corvax-MRP
#  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
