- type: entity
  id: BaseStationGoal
  abstract: true
  # components: # Закоменчено ВЛом, потому что цели другие...
  #   - type: StationGoal
  #     goals:
  #     - Shuttle
  #     - Singularity
  #     - SolarPanels
  #     - Artifacts
  #     - Bank
  #     - Zoo
  #     - MiningOutpost
  #     - Tesla
