using Content.Shared._WL.Emergency;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WL.Communications.UI.Widgets;

/// <summary>
/// A set of controls to change the emergency level for a station.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EmergencyLevelControls : BoxContainer
{
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IPrototypeManager _protoman = default!;

    private bool _emergencyLevelSelectable;
    private ProtoId<EmergencyLevelPrototype>? _currentEmergencyLevel = null;

    public event Action<string>? OnEmergencyLevelChanged;

    public EmergencyLevelControls()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        EmergencyLevelSelector.OnItemSelected += args =>
        {
            EmergencyLevelSelector.Select(args.Id);
            EnableDisableConfirmLevelChangeButton();
        };

        ConfirmEmergencyLevelButton.OnPressed += _ =>
        {
            var metadata = EmergencyLevelSelector.GetItemMetadata(EmergencyLevelSelector.SelectedId);
            if (metadata is ProtoId<EmergencyLevelPrototype> cast)
            {
                OnEmergencyLevelChanged?.Invoke(cast);
            }
        };

        EmergencyLevelSelector.Disabled = !_emergencyLevelSelectable;
    }

    /// <summary>
    /// Updates the UI components to display the current emergency level
    /// and the selectable emergency levels
    /// </summary>
    public void UpdateEmergencyLevels(List<ProtoId<EmergencyLevelPrototype>>? selectableEmergencyLevels, ProtoId<EmergencyLevelPrototype> currentEmergencyLevel, bool emergencyLevelSelectable)
    {
        _emergencyLevelSelectable = emergencyLevelSelectable;
        _currentEmergencyLevel = currentEmergencyLevel;
        CurrentEmergencyLevelLabel.Text = GetLocalizedEmergencyName(currentEmergencyLevel);
        if (_protoman.TryIndex(currentEmergencyLevel, out var emergencyData))
        {
            CurrentEmergencyLevelLabel.ModulateSelfOverride = emergencyData.Color;
        }
        else
        {
            CurrentEmergencyLevelLabel.ModulateSelfOverride = Color.White;
        }

        EmergencyLevelSelector.Disabled = selectableEmergencyLevels == null || !_emergencyLevelSelectable;

        // If user had changed the selection, but hadn't pressed the confirm
        // button at  the point we received an update message, we want to
        // remember what they had selected, so we can attempt to re-select it
        // if it's still an option in the new set of alert level possibilities.
        ProtoId<EmergencyLevelPrototype>? previousSelection = null;
        if (EmergencyLevelSelector.ItemCount > 1)
        {
            var metadata = EmergencyLevelSelector.GetItemMetadata(EmergencyLevelSelector.SelectedId);
            if (metadata is ProtoId<EmergencyLevelPrototype> cast)
            {
                previousSelection = cast;
            }
        }

        // The server will only send alert levels which are selectable, but
        // unfortunately, for a short time after changing the alert level, no
        // level is selectable, so we won't have any levels to put into the
        // alert level list. Here, we make a dummy item to handle that; this
        // item also informs the user what this combo box is for.
        EmergencyLevelSelector.Clear();
        EmergencyLevelSelector.AddItem(Loc.GetString("comms-console-change-emergency-level-button"));
        EmergencyLevelSelector.Select(0);

        if (selectableEmergencyLevels != null)
        {
            foreach (var emergency in selectableEmergencyLevels)
            {
                EmergencyLevelSelector.AddItem(GetLocalizedEmergencyName(emergency));
                EmergencyLevelSelector.SetItemMetadata(EmergencyLevelSelector.ItemCount - 1, emergency);

                if (emergency == previousSelection)
                {
                    EmergencyLevelSelector.Select(EmergencyLevelSelector.ItemCount - 1);
                }
            }
        }

        if (_loc.TryGetString($"comms-console-level-{currentEmergencyLevel}-flavour-label", out var flavour))
        {
            CurrentEmergencyLevelFlavorLabel.Text = flavour;
        }
        else
        {
            CurrentEmergencyLevelFlavorLabel.Text = string.Empty;
        }

        EnableDisableConfirmLevelChangeButton();
    }

    /// <summary>
    /// Configure the "confirm emergency level changed" button to be
    /// consistent with the server state and user interactions
    /// </summary>
    private void EnableDisableConfirmLevelChangeButton()
    {
        // Disable the button when:
        // 1. Server says we can't change level
        // 2. User selected special info option (id 0)
        // 3. User selected the same level the station is currently on
        var selectedId = EmergencyLevelSelector.SelectedId;
        ConfirmEmergencyLevelButton.Disabled = !_emergencyLevelSelectable || selectedId == 0;
        if (selectedId != 0)
        {
            var metadata = EmergencyLevelSelector.GetItemMetadata(selectedId);
            if (metadata is ProtoId<EmergencyLevelPrototype> selected)
            {
                ConfirmEmergencyLevelButton.Disabled |= selected == _currentEmergencyLevel;
            }
        }
    }

    /// <summary>
    /// Utility function to convert an emergency level identifier into a localized string
    /// </summary>
    private string GetLocalizedEmergencyName(ProtoId<EmergencyLevelPrototype> emergencyProto)
    {
        if (_protoman.TryIndex(emergencyProto, out var emergencyData))
        {
            return emergencyData.LocalizedName;
        }

        return emergencyProto;
    }
}
