using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

/// <summary>
/// A generic locking selector.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RequirementsSelector : BoxContainer
{
    private readonly RadioOptions<int> _options;
    private readonly StripeBack _lockStripe;

    public event Action<int>? OnSelected;

    public int Selected => _options.SelectedId;

    public RequirementsSelector()
    {
        RobustXamlLoader.Load(this);
        _options = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleBase.ButtonOpenRight,
            ButtonStyle = StyleBase.ButtonOpenBoth,
            LastButtonStyle = StyleBase.ButtonOpenLeft,
            HorizontalExpand = true,
        };
        //Override default radio option button width
        _options.GenerateItem = GenerateButton;

        _options.OnItemSelected += args =>
        {
            _options.Select(args.Id);
            OnSelected?.Invoke(args.Id);
        };

        var requirementsLabel = new Label()
        {
            Text = Loc.GetString("role-timer-locked"),
            Visible = true,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { StyleBase.StyleClassLabelSubText },
        };

        _lockStripe = new StripeBack()
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                requirementsLabel
            }
        };
    }

    /// <summary>
    /// Actually adds the controls.
    /// </summary>
    public void Setup((string, int/*WL-Skills-start*/, string?, bool?/*WL-Skills-end*/)[] items, Control title, int titleSize, TextureRect? icon = null)
    {
        (string, int, string?, bool?)? first = null;

        foreach (var (text, value/*WL-Skills-start*/, tooltip, disabled/*WL-Skills-end*/) in items)
        {
            if (first == null)
                first = (text, value, tooltip, disabled);

            var id = _options.AddItem(Loc.GetString(text), value);
            _options.Select(id);

            _options.SelectedButton.ToolTip = $"{tooltip}";
            _options.SelectedButton.Disabled = disabled ?? false;
        }

        Select(first!.Value.Item2);

        title.MinSize = new Vector2(titleSize, 0);
        title.MouseFilter = MouseFilterMode.Stop;
        title.Margin = new Thickness(5, 0);

        AddChild(title);

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        var optionsContainer = new BoxContainer()
        {
            SetWidth = 400,
        };

        optionsContainer.AddChild(_options);
        optionsContainer.AddChild(_lockStripe);

        AddChild(optionsContainer);
    }

    public void LockRequirements(FormattedMessage requirements)
    {
        var tooltip = new Tooltip();
        tooltip.SetMessage(requirements);
        _lockStripe.TooltipSupplier = _ => tooltip;
        _lockStripe.Visible = true;
        _options.Visible = false;
    }

    public void UnlockRequirements()
    {
        _lockStripe.Visible = false;
        _options.Visible = true;
    }

    private Button GenerateButton(string text, int value)
    {
        return new Button
        {
            Text = text,
            MinWidth = 90,
            HorizontalExpand = true,
        };
    }

    public void Select(int id)
    {
        _options.Select(id);
    }
}
