using Content.Shared._WL.CCVars;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client._WL.DynamicText.UI;

[GenerateTypedNameReferences]
public sealed partial class DynamicTextWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _configuration = default!;

    public Action<string>? OnDynamicTextSaveButtonPressed;

    private int _maxLength;

    public DynamicTextWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();
        _maxLength = _configuration.GetCVar(WLCVars.MaxDynamicTextLength);

        CDynamicTextInput.Placeholder = new Rope.Leaf(loc.GetString("dynamic-text-placeholder"));
        CDynamicTextInput.OnTextChanged += args => UpdateCharacterCounter(Rope.CalcTotalLength(args.TextRope));
        DynamicTextSaveButton.OnPressed += OnDynamicTextSave;
        DynamicTextCloseButton.OnPressed += _ => Close();
        UpdateCharacterCounter(0);
    }

    public void SetDynamicText(string text)
    {
        CDynamicTextInput.TextRope = new Rope.Leaf(text);
        UpdateCharacterCounter(text.Length);
    }

    private void OnDynamicTextSave(BaseButton.ButtonEventArgs obj)
    {
        if (Rope.CalcTotalLength(CDynamicTextInput.TextRope) > _maxLength)
            return;

        OnDynamicTextSaveButtonPressed?.Invoke(Rope.Collapse(CDynamicTextInput.TextRope).Trim());
    }

    private void UpdateCharacterCounter(long length)
    {
        CharacterCounter.Text = Loc.GetString(
            "dynamic-text-character-counter",
            ("current", length),
            ("maximum", _maxLength));
        CharacterCounter.ModulateSelfOverride = length > _maxLength ? Color.Red : null;
        DynamicTextSaveButton.Disabled = length > _maxLength;
    }
}
