using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._WL.DynamicText.UI;

[GenerateTypedNameReferences]
public sealed partial class DynamicTextWindow : FancyWindow
{
    public Action<string>? OnDynamicTextChanged;
    public Action? OnDynamicTextSaveButtonPressed;
    public DynamicTextWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();

        CDynamicTextInput.Placeholder = new Rope.Leaf(loc.GetString("dynamic-text-placeholder"));
        CDynamicTextInput.OnTextChanged += _ => DynamicTextChanged();

        DynamicTextSaveButton.OnPressed += OnDynamicTextSave;
    }

    public void DynamicTextChanged()
    {
        // OnDynamicTextChanged?.Invoke(Rope.Collapse(CDynamicTextInput.TextRope).Trim());
    }

    private void OnDynamicTextSave(BaseButton.ButtonEventArgs obj)
    {
        // OnDynamicTextSaveButtonPressed?.Invoke();

    }
}
